### ISSUE TITLE
Landing: Slider component

### ISSUE THREAD

**Issue by m7ez1n** [he4rt/he4rt-landing-ssr#10]
Criar o componente de slider que é exibido na landing page
![image](https://user-images.githubusercontent.com/44484286/208832075-c4362d79-d8d5-4300-a2ba-bdf4141855c9.png)

**Comment by Rychillie** [comment]
Estou realizando o desenvolvimento desta Issue

**Comment by danielhe4rt** [comment]
@Rychillie vamos deixar aguardando pra mergear posteriormente sua branch. Creio que esteja tudo certo já.
