### ISSUE TITLE
Elementos da landing antiga para a nova

### ISSUE THREAD

**Issue by kjkGustavo** [he4rt/he4rt-landing-ssr#14]
Utilizar elementos da landing antiga na parte inferior. (a.k.a CTRL C + CTRL V)

**Obervações**
- Não é necessário a componentização desses elementos, pois terá uma issue nova para componentizar os components do novo figma.

**Motivo:**
- Visando uma entrega mais rápida e com o foco total no perfil, seria a decisão com mais ganho.

Elementos da landing anterior:
![image](https://user-images.githubusercontent.com/47262260/209734776-2546e99f-723d-48e7-a4b7-aedc17091483.png)

**Comment by slmeduardo** [comment]
eu posso pegar essa issue e levar os elementos da antiga
