### ISSUE TITLE
Landing: Parceiros

### ISSUE THREAD

**Issue by kjkGustavo** [he4rt/he4rt-landing-ssr#16]
Componentizar cards e criar a seção de parceiros da He4rt.

Figma: https://www.figma.com/file/vCJ4Cd2SBXcdB1jiwzHmnS/%F0%9F%92%9C-%7C-He4rt-Devs?node-id=2%3A3&t=mjuSbcoMeUSazLn1-0

Section:
![image](https://user-images.githubusercontent.com/47262260/209736800-0d8b8f90-9c31-4f56-957a-65334b012f02.png)

**Comment by slmeduardo** [comment]
eu posso fazer essa section
