### ISSUE TITLE
Landing: Recordes

### ISSUE THREAD

**Issue by kjkGustavo** [he4rt/he4rt-landing-ssr#17]
Criar seção, componentizar os cards de recordes e textos.

![image](https://user-images.githubusercontent.com/47262260/209736846-57b55f30-c356-468c-ab2a-6978dd505faa.png)

**Comment by Rychillie** [comment]
@kjkGustavo pode assinar a minha pessoa esta issue

**Comment by Rychillie** [comment]
Nova PR: #21
