### ISSUE TITLE
Profile: page

### ISSUE THREAD

**Issue by kjkGustavo** [he4rt/he4rt-landing-ssr#18]
Deverá ser feito uma nova rota para o perfil de usuário da He4rt.

Requisitos:
- Mobile Responsivo
- Componentização dos Cards e informações

![image](https://user-images.githubusercontent.com/47262260/209737133-4005172e-bee7-4ded-b3a2-8cf272b3de09.png)

## API
* Rota `api/users/discord_id` *(Me chama discord que forneço acesso a API)*

* Retorno:
```json
{
    "id": 1,
    "discord_id": 426540070028443688,
    "twitch_id": null,
    "email": null,
    "name": "Gustavo Lima",
    "nickname": "kjkGustavo",
    "git": "https:\/\/github.com\/kjkGustavo",
    "linkedin": "https:\/\/www.linkedin.com\/in\/kjkGustavo",
    "about": "Me chamo Gustavo e vejo programação desde os 11 anos",
    "level": 33,
    "current_exp": 4737,
    "money": "80308.00",
    "daily": "2022-11-30T01:41:54.000000Z",
    "is_donator": true,
    "created_at": "2020-11-21T02:53:47.000000Z",
    "updated_at": "2022-12-27T22:35:58.000000Z",
}
```

**Comment by danielhe4rt** [comment]
Salve! Se precisar de ajuda com essa tarefa, podemos dividir em componentes menores.

**Comment by m7ez1n** [comment]
Vou fechar essa issue pois as duas outras que eram dependentes já foram mergeadas
