### ISSUE TITLE
Data de entrada na comunidade

### ISSUE THREAD

**Issue by danielhe4rt** [he4rt/he4rt-landing-ssr#22]
![image](https://user-images.githubusercontent.com/6912596/210181244-edfbb4f9-d971-48c6-b916-0261d62a555c.png)

Fiquei pensando em tentar trazer uma ideia de mostrar há quanto tempo a pessoa está na comunidade pra mostrar a curva de engajamento dela.

Algo como: entrou há 4 dias/ 4 meses e 2 dias/ 2 anos e 4 meses.

O que vocês acham?

**Comment by SamucaDev** [comment]
Gostei da ideia, algo parecido com isso?

"Contribuindo há 1 ano e 4 meses. 💜 "

Aonde poderiamos colocar?

**Comment by m7ez1n** [comment]
@DanielHe4rt para colocar a data de entrada devemos considerar o created_at ?
![image](https://user-images.githubusercontent.com/44484286/213609399-9eae58e4-d466-488e-826e-723572567871.png)
