### ISSUE TITLE
Barra de XP no perfil do usuário

### ISSUE THREAD

**Issue by m7ez1n** [he4rt/he4rt-landing-ssr#30]
Uma outra feature da página de perfil é a barra de XP do usuário, também é necessária para que consigamos concluir a task #18 

![image](https://user-images.githubusercontent.com/44484286/212802307-f2be0e03-1245-4057-af44-0115220e685d.png)

**Comment by cherryramatisdev** [comment]
Consigo assumir essa issue se estiver disponivel!

**Comment by m7ez1n** [comment]
Só vai @cherryramatisdev será de grande ajuda a sua contribuição <3

**Comment by cherryramatisdev** [comment]
Opa @m7he4rt ou @kjkGustavo podem me fornecer um `discord_id` para chamar na API? Tentei a que foi informada na #18 mas acredito ser um mock ou algo parecido

Posso mockar a request caso a rota não esteja pronta ainda, mas pelo que olhei na codebase parece pronta

**Comment by m7ez1n** [comment]
pode pegar de qualquer usuário: 

- Gustavo -> 426540070028443688
- Daniel -> 204122995579551744

Pra pegar de um usuário que deseja testar é só ir no discord clicar com botão direito e copiar o ID
